apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: dockerhub-nyndow/my-python-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
